### ISSUE TITLE
[CT] Hitting the Fragment of Fate with Eruption doesnt count as a mistake

### ISSUE THREAD

**Issue by ElAtiendeBoludos** [WCGH/FRU-Sim#2]
As the title says, if you hit the crystal with the Eruption (The purple Spread) during CT you will not get told you did a mistake. 

While hitting it with the Unholy (the yellow stack) will mark it as a mistake.

**Comment by ElAtiendeBoludos** [comment]
Actually the issue is that the Eruption doesnt have an AOE at all, theres no explosion going off. Debuff just disappears

**Comment by WCGH** [comment]
Resolved in latest update. Thanks for the report.
