### ISSUE TITLE
[lr] Ldpu adjust spots not used

### ISSUE THREAD

**Issue by celestia369** [WCGH/FRU-Sim#5]
In LR when LDPU is set the offtank tries to take the inner position on 2, where in ldpu OT takes the outer position on B and MT takes 2

**Comment by WCGH** [comment]
Are you talking about the initial setup for Light Rampant? Not sure what you mean by inner and outer positions.

**Comment by celestia369** [comment]
Actually after checking its just that the bots position in a much subtler curve compared to what i usually see in pf which puts the inner posotions tigher  in, apologies for the mistake
