### ISSUE TITLE
Sextuple Apocalyps

### ISSUE THREAD

**Issue by DerWici** [WCGH/FRU-Sim#6]
Hello :)

First of all thanks for programming that tool.
I just noticed, that in Sextuple Apo LPDU Permaswap Tank 2 is bating the Tank buster. 
In the raidplan that LPDU provids Tank 1 is planed for that.

**Comment by WCGH** [comment]
Fixed in 1.4.3, thanks for the report!

**Comment by DerWici** [comment]
Hey, I noticed an inconsistency in the LPDU Strat. The raidplan (where MT is tanking the bait) they referring to doesn't match the mitigation plan(where OT is tanking the bait). I've seen both ways now in party finder. Just wanted to let you know.
